version: '3'

services:
  api:
    restart: always
    container_name: api
    build: ./api
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - ./api:/app
    env_file:
      - ./.env

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "challenge"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    env_file:
      - ./.env
    environment:
      REACT_APP_GOOGLE_APY_KEY: $GOOGLE_APY_KEY

volumes:
  postgres_data:
